name: dallasseo
favicon: null
layout_spectrum: 0.8482326134108007
typography_spectrum: 0.6469197496771812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.049886640161275864
  lightness: 0.5320776323787868
  saturation: 0.3074837392196059
  rhythmicContrast: 0.008233493659645319
purpose: []
